name: Deploy Frontend

on:
  push:
    branches:
      - main  # Đảm bảo nhánh này trùng với nhánh bạn đang code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build
        run: |
          # 1. Cài đặt toàn bộ dependencies (bao gồm cả devDependencies để có Vite)
          npm install
          
          # 2. Cấp quyền thực thi cho các file binary trong node_modules (Fix lỗi Permission denied)
          chmod +x ./node_modules/.bin/vite
          
          # 3. Sử dụng npx để chạy build cho an toàn
          npx vite build

      - name: Deploy to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*" # React thường build ra folder dist
          target: "/home/ubuntu/wham-ui"
          strip_components: 1

      - name: Reload Nginx (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo systemctl reload nginx
